name: example
description: A new Flutter project.

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  bdlogging:
    path: ..

dev_dependencies:
  flutter_code_style:
    git: https://github.com/MoovBuilder983/flutter-code-style.git
