name: bdlogging
description: A Flutter package that provide logging capability for flutter apps.
version: 1.0.0
homepage: https://github.com/bitsydarel/bdlogging

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  http: ^1.1.0
  intl: ^0.18.1
  io: ^1.0.4
  meta: ^1.9.0
  path: ^1.8.3

dev_dependencies:
  flutter_code_style:
    git: https://github.com/MoovBuilder983/flutter-code-style.git
  mocktail: ^0.3.0
  test: ^1.24.4
