name: bdlogging_firebase
description: A Flutter package that provide BDLogHandler for firebase services.
version: 1.0.0
homepage: https://github.com/bitsydarel/bdlogging

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  bdlogging:
    path: ..
  firebase_crashlytics: ^3.3.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_code_style:
    git: https://github.com/MoovBuilder983/flutter-code-style.git
  flutter_test:
    sdk: flutter
